import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';

const pages = {
  privacy: {
    title: '🔒 Privacy Policy',
    lastUpdated: 'February 2026',
    sections: [
      {
        title: '1. Information We Collect',
        content: `When you create an account on Quiz Buzz, we collect:
- Your name and email address (via Google login or email signup)
- Your profile photo (if using Google login)
- Quiz scores, XP points, and game history
- Device information for app performance`
      },
      {
        title: '2. How We Use Your Data',
        content: `We use your information to:
- Create and manage your Quiz Buzz account
- Display your scores on the leaderboard
- Track your XP, level, and quiz history
- Enable friend challenges and multiplayer features
- Improve app performance and user experience`
      },
      {
        title: '3. Data Security',
        content: `Your data is stored securely using Google Firebase, which provides industry-standard encryption. We do not share your personal information with third-party advertisers. Your email and profile data are only used within Quiz Buzz.`
      },
      {
        title: '4. Google Authentication',
        content: `When you sign in with Google, we only access your public profile information (name, email, and photo). We do not access your Google contacts, emails, or any other Google services data.`
      },
      {
        title: '5. Cookies & Local Storage',
        content: `Quiz Buzz uses local storage to keep you logged in securely between sessions. We do not use tracking cookies or share browsing data with any third parties.`
      },
      {
        title: '6. Children\'s Privacy',
        content: `Quiz Buzz is designed for users of all ages. We do not knowingly collect personal information from children under 13 without parental consent. Parents can contact us to request deletion of their child's data.`
      },
      {
        title: '7. Your Rights',
        content: `You have the right to:
- Access your personal data at any time
- Delete your account and all associated data
- Opt out of leaderboard display
- Update your profile information`
      },
      {
        title: '8. Contact Us',
        content: `If you have questions about this Privacy Policy, please contact us at:\n📧 admin@quizbuzz.com`
      }
    ]
  },
  terms: {
    title: '📋 Terms of Service',
    lastUpdated: 'February 2026',
    sections: [
      {
        title: '1. Acceptance of Terms',
        content: `By using Quiz Buzz, you agree to these Terms of Service. If you do not agree, please do not use the app. We reserve the right to update these terms at any time.`
      },
      {
        title: '2. User Accounts',
        content: `• You must provide accurate information when creating an account
- You are responsible for keeping your password secure
- You may not create accounts for others without permission
- One account per person is allowed
- We reserve the right to suspend accounts that violate our rules`
      },
      {
        title: '3. Acceptable Use',
        content: `You agree NOT to:
- Cheat or use automated tools to gain unfair advantages
- Harass, bully, or abuse other players in chat
- Share inappropriate content through the chat feature
- Attempt to hack or disrupt the Quiz Buzz service
- Use the app for any illegal purpose`
      },
      {
        title: '4. Quiz Content',
        content: `Quiz questions are generated by AI and reviewed for accuracy. While we strive for accuracy, Quiz Buzz is not responsible for any errors in quiz content. If you find incorrect questions, please report them to our admin team.`
      },
      {
        title: '5. Multiplayer & Chat',
        content: `Quiz Buzz includes multiplayer challenges and chat features. You are responsible for your conduct in these features. Abusive behavior will result in account suspension. Friend chat is monitored for safety purposes.`
      },
      {
        title: '6. Intellectual Property',
        content: `Quiz Buzz and all its content, including the logo, design, and quiz questions, are owned by Quiz Buzz. You may not copy, reproduce, or distribute any part of the app without written permission.`
      },
      {
        title: '7. Disclaimer',
        content: `Quiz Buzz is provided "as is" without any warranties. We do not guarantee uninterrupted service. We are not responsible for any data loss or damages arising from use of the app.`
      },
      {
        title: '8. Contact',
        content: `For questions about these Terms of Service:\n📧 admin@quizbuzz.com`
      }
    ]
  },
  about: {
    title: '🐝 About Quiz Buzz',
    lastUpdated: 'February 2026',
    sections: [
      {
        title: 'What is Quiz Buzz?',
        content: `Quiz Buzz is an AI-powered quiz platform that lets you test your knowledge across 9+ categories including General Knowledge, Science, History, Sports, and more. Challenge friends, climb the leaderboard, and earn XP as you learn!`
      },
      {
        title: '🤖 AI-Powered Questions',
        content: `Quiz Buzz uses advanced AI (powered by Meta's Llama 3.3) to generate fresh, unique quiz questions. Our smart system saves questions so they load instantly for future players, while continuously adding new content in the background.`
      },
      {
        title: '🏆 Features',
        content: `• 9+ quiz categories with 50+ questions each
- AI-generated questions that never repeat
- Real-time multiplayer challenges
- Friend system with live chat
- XP & leveling system
- Global leaderboard
- Quiz history tracking
- Google & email authentication
- Works on all devices`
      },
      {
        title: '👨‍💻 Built With',
        content: `• Frontend: React.js
- Backend: Node.js + Express
- Database: Google Firebase Firestore
- Auth: Firebase Authentication
- AI: OpenRouter (Llama 3.3 70B)
- Real-time: Socket.io`
      },
      {
        title: '📬 Contact',
        content: `Have feedback or found a bug? We'd love to hear from you!\n📧 admin@quizbuzz.com`
      }
    ]
  }
};

export default function Legal() {
  const navigate = useNavigate();
  const [activePage, setActivePage] = useState('privacy');
  const page = pages[activePage];

  return (
    <div style={{ maxWidth: '800px', margin: '0 auto', padding: '40px 20px' }}>

      {/* Tab Selector */}
      <div style={{ display: 'flex', gap: '8px', marginBottom: '32px',
        justifyContent: 'center' }}>
        {Object.keys(pages).map(key => (
          <button key={key} onClick={() => setActivePage(key)} style={{
            padding: '10px 20px', borderRadius: '50px',
            border: `2px solid ${activePage === key ? '#7B2FFF' : 'rgba(255,255,255,0.15)'}`,
            background: activePage === key ? 'rgba(123,47,255,0.2)' : 'transparent',
            color: activePage === key ? '#fff' : 'rgba(255,255,255,0.5)',
            fontFamily: "'Fredoka One', cursive", fontSize: '0.95rem',
            cursor: 'pointer'
          }}>
            {pages[key].title.split(' ')[0]} {pages[key].title.split(' ').slice(1).join(' ')}
          </button>
        ))}
      </div>

      {/* Page Content */}
      <div style={{ background: '#16213E', borderRadius: '24px', padding: '36px',
        border: '1px solid rgba(255,255,255,0.08)' }}>

        {/* Header */}
        <div style={{ textAlign: 'center', marginBottom: '32px',
          paddingBottom: '24px', borderBottom: '1px solid rgba(255,255,255,0.08)' }}>
          <div style={{ fontFamily: "'Fredoka One', cursive",
            fontSize: '2.2rem', marginBottom: '8px' }}>
            {page.title}
          </div>
          <div style={{ color: 'rgba(255,255,255,0.4)', fontSize: '0.85rem' }}>
            Quiz Buzz • Last updated: {page.lastUpdated}
          </div>
        </div>

        {/* Sections */}
        {page.sections.map((section, i) => (
          <div key={i} style={{ marginBottom: '28px' }}>
            <div style={{ fontFamily: "'Fredoka One', cursive",
              fontSize: '1.15rem', color: '#FFD60A', marginBottom: '10px' }}>
              {section.title}
            </div>
            <div style={{ color: 'rgba(255,255,255,0.7)', lineHeight: 1.8,
              fontSize: '0.92rem', whiteSpace: 'pre-line' }}>
              {section.content}
            </div>
          </div>
        ))}

        {/* Footer */}
        <div style={{ marginTop: '32px', paddingTop: '24px',
          borderTop: '1px solid rgba(255,255,255,0.08)',
          textAlign: 'center', color: 'rgba(255,255,255,0.3)',
          fontSize: '0.8rem' }}>
          © 2026 Quiz Buzz 🐝 All rights reserved
        </div>
      </div>

      {/* Back Button */}
      <button onClick={() => navigate('/')} style={{
        display: 'block', margin: '24px auto 0',
        background: 'linear-gradient(135deg, #7B2FFF, #FF3D9A)',
        border: 'none', color: '#fff', padding: '14px 32px',
        borderRadius: '50px', fontFamily: "'Fredoka One', cursive",
        fontSize: '1rem', cursor: 'pointer'
      }}>🏠 Back to Home</button>
    </div>
  );
}